
name: K6 Performance Tests

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      test_file:
        description: 'The k6 test file to run '
        required: false
        default: ''

jobs:
  k6_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates gnupg
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --yes --dearmor -o /etc/apt/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/etc/apt/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run test(s)
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.test_file }}" ]; then
            echo "Manually running k6 test file: ${{ github.event.inputs.test_file }}"
            k6 run "${{ github.event.inputs.test_file }}"
          else
            echo "Running all k6 tests on PR from feature/k6_demo"
            for file in ./*.js; do
              echo "Running $file"
              k6 run "$file"
            done
          fi
        shell: bash
    if: github.head_ref == 'feature/k6_demo' || github.event_name == 'workflow_dispatch'
